#!/usr/bin/env bash

ACTION=$1
DEBUG=0
WORKING_DIR=$HOME

ERROR=`tput setaf 1`
SUCCESS=`tput setaf 2`
WARNING=`tput setaf 3`
INFO=`tput setaf 4`
RESET=`tput sgr0`

function debug {
	if [ $DEBUG -eq 1 ]; then
		MSG=$1
		echo "`tput setab 3``tput setaf 0`[DEBUG] ${MSG}${RESET}"
	fi
}

# Print out an error message.
function error {
	MSG=$1
	echo "${ERROR}${MSG}${RESET}"
}

# Print out an info message.
function info {
	MSG=$1
	echo "${INFO}${MSG}${RESET}"
}

# Print out a success message.
function success {
	MSG=$1
	echo "${SUCCESS}${MSG}${RESET}"
}

# Print out a success message.
function warning {
	MSG=$1
	echo "${WARNING}${MSG}${RESET}"
}

# Check if the application is installed in the system.
function check_application {
	NAME=$1
	APP=$2

	debug "Checking application: ${NAME}"

	if hash $APP 2>/dev/null; then
		debug "${NAME} installed."
		return
	else
		debug "${NAME} not installed."
		error "Please install ${NAME} on your system."
		exit 1
	fi
}

# Check for the dependencies.
function check_dependencies {
	info "Checking for dependencies."

	check_application Git git
	check_application Vim vim
	check_application "Z Shell" zsh
	check_directory $WORKING_DIR/.oh-my-zsh "Please make sure you've installed 'oh-my-zsh'."

	success "All good."
}

# Check if the directory exist.
function check_directory {
	DIRECTORY=$1
	MSG=$2

	debug "Checking directory: ${DIRECTORY}"

	if [ -d "$DIRECTORY" ]; then
		debug "${DIRECTORY} exists."
		return
	else
		debug "${DIRECTORY} does not exist."

		if [ -z "$MSG" ]; then
			debug "Custom MSG not set."
			error "Please make sure '${DIRECTORY}' exists."
		else
			debug "Custom MSG set."
			error "$MSG"
		fi
		exit 1
	fi
}

# Copy the file from A to B.
function copy {
	SRC=$1
	DIST=$2
	FLAGS=$3

	info "Copying ${SRC}"

	if [ -n "$FLAGS" ]; then
		debug "Flags '${FLAGS}' passed."

		if [ -d "$SRC" ]; then debug "D"; else debug "ND"; fi
		if [[ $FLAGS == *"d"* ]] && [ -d "$SRC" ]; then
			debug "-d flag detected."
			CP_FLAGS=${CP_FLAGS}"R"
		fi

		if [ -f $DIST ]; then debug "E"; else debug "NE"; fi
		if [[ $FLAGS == *"O"* ]] && [ -f $DIST ]; then
			debug "-O flag detected."
			CP_FLAGS=${CP_FLAGS}"rf"
		fi
	fi

	if [ -n "$CP_FLAGS" ]; then
		debug "Custom 'cp -${CP_FLAGS}' flags established."
		cp -${CP_FLAGS} ${SRC} ${DIST}
	else
		debug "No custom flags established."
		cp ${SRC} ${DIST}
	fi

	debug "Unsetting CP_FLAGS"
	unset CP_FLAGS
}

# Initialise the environment for the developer.
function init {
	info "Initialising environment."
	check_dependencies

	copy ./.vimrc $WORKING_DIR/.vimrc -O
	copy ./.aliases.rp $WORKING_DIR/.aliases.rp -O
	copy ./.alias $WORKING_DIR/.alias -Od
	copy ./.custom.rp $WORKING_DIR/.custom.rp -O
	copy ./.exports.rp $WORKING_DIR/.exports.rp -O
	copy ./.oh-my-zsh/themes/honukai.zsh-theme $WORKING_DIR/.oh-my-zsh/themes/honukai.zsh-theme -O

	success "Your environment has been initialised."
}

# List the functionality covered by this application.
function list {
	echo -e "Display the list of functionality supported by DevEnv.\n"

	echo -e "list\tLists any functionality covered by this application."
	echo -e "init\tInitialises the developer environment. ${WARNING}This will override any existing setup!${RESET}"
	echo -e "update\tUpdates the most important files with the new ones. ${WARNING}This will override important files.${RESET}"
}

# Update the environment for the developer.
function update {
	info "Updating environment."
	check_dependencies

	copy ./.vimrc $WORKING_DIR/.vimrc -O
	copy ./.aliases.rp $WORKING_DIR/.aliases.rp -O
	copy ./.alias $WORKING_DIR/.alias -d
	copy ./.custom.rp $WORKING_DIR/.custom.rp
	copy ./.exports.rp $WORKING_DIR/.exports.rp
	copy ./.oh-my-zsh/themes/honukai.zsh-theme $WORKING_DIR/.oh-my-zsh/themes/honukai.zsh-theme -O

	success "Your environment has been updated."
}

###############################

case $ACTION in
	init ) init;;
	update ) update;;
	* ) list;
esac
