alias chenv='choose_environment'
alias df='df --human-readable'
alias du='du --total --human-readable'
alias g='git'
alias k='kubectl'
alias ls='ls --color=tty --human-readable'
alias ping='ping -c 5'
alias ports='netstat -tulanp'
alias top='atop'
